function cellInfo = bus_obj(varargin) 
% BUS_OBJ returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'UDP_Packet', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'IP_Address', [4 1], 'uint8', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'IP_Port', 1, 'uint16', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Length', 1, 'uint16', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Data', [16 1], 'uint8', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
